declare const _default: import("vue").DefineComponent<{
    modelValue: {
        type: (DateConstructor | ArrayConstructor)[];
    };
    dayNames: ArrayConstructor;
    monthNames: ArrayConstructor;
    firstDayOfWeek: NumberConstructor;
    events: ArrayConstructor;
    indicators: StringConstructor;
    minDate: DateConstructor;
    maxDate: DateConstructor;
    focused: ObjectConstructor;
    disabled: BooleanConstructor;
    dateCreator: FunctionConstructor;
    unselectableDates: ArrayConstructor;
    unselectableDaysOfWeek: ArrayConstructor;
    selectableDates: ArrayConstructor;
    nearbyMonthDays: BooleanConstructor;
    nearbySelectableMonthDays: BooleanConstructor;
    showWeekNumber: BooleanConstructor;
    weekNumberClickable: BooleanConstructor;
    rulesForFirstWeek: NumberConstructor;
    range: BooleanConstructor;
    multiple: BooleanConstructor;
    tableClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableHeadClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableHeadCellClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableBodyClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableRowClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellSelectedClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellFirstSelectedClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellInvisibleClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellWithinSelectedClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellLastSelectedClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellFirstHoveredClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellWithinHoveredClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellLastHoveredClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellTodayClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellSelectableClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellUnselectableClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellNearbyClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableCellEventsClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableEventClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableEventIndicatorsClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableEventsClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
    tableEventVariantClass: (ArrayConstructor | StringConstructor | FunctionConstructor)[];
}, unknown, {
    selectedBeginDate: any;
    selectedEndDate: any;
    hoveredEndDate: any;
}, {
    tableClasses(): any[];
    tableHeadClasses(): any[];
    tableHeadCellClasses(): any[];
    tableBodyClasses(): any[];
    tableCellClasses(): any[];
    visibleDayNames(): any[];
    eventsInThisMonth(): any[];
    weeksInThisMonth(): any[];
    hoveredDateRange(): any[];
}, {
    updateSelectedDate(date: any): void;
    handleSelectRangeDate(date: any): void;
    handleSelectMultipleDates(date: any): void;
    weekBuilder(startingDate: any, month: any, year: any): any[];
    validateFocusedDay(): void;
    selectableDate(day: any): boolean;
    eventsInThisWeek(week: any): any;
    setRangeHoverEndDate(day: any): void;
    changeFocus(day: any): void;
}, import("vue").DefineComponent<{
    override: BooleanConstructor;
}, unknown, unknown, {}, {
    computedClass(field: string, defaultValue: string, suffix?: string): string;
}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, Record<string, any>, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<{} & {
    override?: boolean;
}>, {}>, import("vue").ComponentOptionsMixin, ("update:modelValue" | "range-start" | "range-end" | "update:focused")[], "update:modelValue" | "range-start" | "range-end" | "update:focused", import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<{} & {
    modelValue?: string | unknown[];
    disabled?: boolean;
    multiple?: boolean;
    showWeekNumber?: boolean;
    minDate?: string;
    maxDate?: string;
    unselectableDates?: unknown[];
    unselectableDaysOfWeek?: unknown[];
    selectableDates?: unknown[];
    events?: unknown[];
    indicators?: string;
    dateCreator?: Function;
    nearbyMonthDays?: boolean;
    nearbySelectableMonthDays?: boolean;
    weekNumberClickable?: boolean;
    range?: boolean;
    rulesForFirstWeek?: number;
    firstDayOfWeek?: number;
    tableRowClass?: string | Function | unknown[];
    tableCellClass?: string | Function | unknown[];
    tableCellSelectedClass?: string | Function | unknown[];
    tableCellFirstSelectedClass?: string | Function | unknown[];
    tableCellWithinSelectedClass?: string | Function | unknown[];
    tableCellLastSelectedClass?: string | Function | unknown[];
    tableCellFirstHoveredClass?: string | Function | unknown[];
    tableCellInvisibleClass?: string | Function | unknown[];
    tableCellWithinHoveredClass?: string | Function | unknown[];
    tableCellLastHoveredClass?: string | Function | unknown[];
    tableCellTodayClass?: string | Function | unknown[];
    tableCellSelectableClass?: string | Function | unknown[];
    tableCellUnselectableClass?: string | Function | unknown[];
    tableCellNearbyClass?: string | Function | unknown[];
    tableCellEventsClass?: string | Function | unknown[];
    tableEventClass?: string | Function | unknown[];
    tableEventIndicatorsClass?: string | Function | unknown[];
    tableEventsClass?: string | Function | unknown[];
    tableEventVariantClass?: string | Function | unknown[];
    dayNames?: unknown[];
    monthNames?: unknown[];
    focused?: Record<string, any>;
    tableClass?: string | Function | unknown[];
    tableHeadClass?: string | Function | unknown[];
    tableHeadCellClass?: string | Function | unknown[];
    tableBodyClass?: string | Function | unknown[];
}>, {}>;
export default _default;
