<template>
    <section>
        <o-breadcrumb>
            <breadcrumb-item>Home</breadcrumb-item>
            <breadcrumb-item>Docs</breadcrumb-item>
            <breadcrumb-item>Breadcrumb</breadcrumb-item>
        </o-breadcrumb>
    </section>
</template>
