name: Generate Release
on:
  push:
    tags:
      - v*

permissions:
  id-token: write # Required for OIDC
  contents: write # Required to create GitHub Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # Always release the tag ${GITHUB_REF} version

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies 📦
        run: npm ci

      - name: Build packages 🛠️
        run: npm run build

      - name: Install release dependency 📦
        run: npm i extract-changelog-release

      - name: Generate release body 📝
        run: npx extract-changelog-release > RELEASE_BODY.md

      - name: Create GitHub release 🎉
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "RELEASE_BODY.md"
          # define prerelease based on the tag name
          prerelease: ${{ contains(github.ref, '-pre.') }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Oruga pre-release 🐛
        if: ${{ contains(github.ref, '-pre.') }} # only for pre-release
        working-directory: ./packages/oruga
        run: npm publish --tag pre

      - name: Publish Oruga release 🐛
        if: ${{ !contains(github.ref, '-pre.') }} # only for main release
        working-directory: ./packages/oruga
        run: npm publish

      - name: Publish Examples pre-release 🦋
        if: ${{ contains(github.ref, '-pre.') }} # only for pre-release
        working-directory: ./packages/examples
        run: npm publish --tag pre

      - name: Publish Examples release 🦋
        if: ${{ !contains(github.ref, '-pre.') }} # only for main release
        working-directory: ./packages/examples
        run: npm publish

      - name: Publish documentation 📰
        # only update documentation for main releases
        if: ${{ !contains(github.ref, '-pre.') }}
        run: |
          git fetch origin develop:develop
          git push origin develop:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
